SET(CMAKE_C_COMPILER   "/usr/bin/clang"        CACHE FILEPATH "")
SET(CMAKE_CXX_COMPILER "/usr/bin/clang++"      CACHE FILEPATH "")
SET(CMAKE_AR           "/usr/bin/llvm-ar"      CACHE FILEPATH "")
SET(CMAKE_LINKER       "/usr/bin/llvm-ld"      CACHE FILEPATH "")
SET(CMAKE_NM           "/usr/bin/llvm-nm"      CACHE FILEPATH "")
SET(CMAKE_OBJDUMP      "/usr/bin/llvm-objdump" CACHE FILEPATH "")
SET(CMAKE_RANLIB       "/usr/bin/llvm-ranlib"  CACHE FILEPATH "")
