/* A parser generated by PackCC 3.0.0 */

#ifdef _MSC_VER
#undef _CRT_NONSTDC_NO_WARNINGS
#undef _CRT_SECURE_NO_WARNINGS
#define _CRT_NONSTDC_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif /* _MSC_VER */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "empty.h"

#if !defined __has_attribute || defined _MSC_VER
#define __attribute__(x)
#endif

#ifdef _MSC_VER
#define MARK_FUNC_AS_USED __pragma(warning(suppress:4505))
#else
#define MARK_FUNC_AS_USED __attribute__((__unused__))
#endif

#ifdef _MSC_VER
#define MARK_VAR_AS_USED __pragma(warning(suppress:4189))
#else
#define MARK_VAR_AS_USED __attribute__((__unused__))
#endif

#ifndef PCC_BUFFER_MIN_SIZE
#define PCC_BUFFER_MIN_SIZE 256
#endif /* !PCC_BUFFER_MIN_SIZE */

#ifndef PCC_ARRAY_MIN_SIZE
#define PCC_ARRAY_MIN_SIZE 2
#endif /* !PCC_ARRAY_MIN_SIZE */

#ifndef PCC_THUNK_ARRAY_MIN_SIZE
#define PCC_THUNK_ARRAY_MIN_SIZE 2
#endif /* !PCC_THUNK_ARRAY_MIN_SIZE */

#ifndef PCC_LR_MEMO_MAP_MIN_SIZE
#define PCC_LR_MEMO_MAP_MIN_SIZE 4
#endif /* !PCC_LR_MEMO_MAP_MIN_SIZE */

#ifndef PCC_POOL_MIN_SIZE
#define PCC_POOL_MIN_SIZE 65536
#endif /* !PCC_POOL_MIN_SIZE */

#define PCC_DBG_EVALUATE 0
#define PCC_DBG_MATCH    1
#define PCC_DBG_NOMATCH  2

#define PCC_VOID_VALUE (~(size_t)0)

typedef enum pcc_bool_tag {
    PCC_FALSE = 0,
    PCC_TRUE
} pcc_bool_t;

typedef struct pcc_char_array_tag {
    size_t m, n;
    char *p;
} pcc_char_array_t;

typedef struct pcc_range_tag {
    size_t start;
    size_t end;
} pcc_range_t;

typedef int pcc_value_t;

typedef void *pcc_auxil_t;

typedef struct pcc_value_table_tag {
    size_t m, n;
    pcc_value_t *p;
} pcc_value_table_t;

typedef struct pcc_value_refer_table_tag {
    size_t m, n;
    pcc_value_t **p;
} pcc_value_refer_table_t;

typedef struct pcc_capture_tag {
    pcc_range_t range;
    pcc_char_array_t string; /* mutable */
} pcc_capture_t;

typedef struct pcc_capture_table_tag {
    size_t m, n;
    pcc_capture_t *p;
} pcc_capture_table_t;

typedef struct pcc_capture_const_table_tag {
    size_t m, n;
    const pcc_capture_t **p;
} pcc_capture_const_table_t;

typedef struct pcc_thunk_tag pcc_thunk_t;
typedef struct pcc_thunk_array_tag pcc_thunk_array_t;

typedef void (*pcc_action_t)(pcc_context_t *, pcc_thunk_t *, pcc_value_t *);

typedef enum pcc_thunk_type_tag {
    PCC_THUNK_LEAF,
    PCC_THUNK_NODE
} pcc_thunk_type_t;

typedef struct pcc_thunk_leaf_tag {
    pcc_value_refer_table_t values;
    pcc_capture_const_table_t capts;
    pcc_capture_t capt0;
    pcc_action_t action;
} pcc_thunk_leaf_t;

typedef struct pcc_thunk_node_tag {
    const pcc_thunk_array_t *thunks; /* just a reference */
    pcc_value_t *value; /* just a reference */
} pcc_thunk_node_t;

typedef union pcc_thunk_data_tag {
    pcc_thunk_leaf_t leaf;
    pcc_thunk_node_t node;
} pcc_thunk_data_t;

struct pcc_thunk_tag {
    pcc_thunk_type_t type;
    pcc_thunk_data_t data;
};

struct pcc_thunk_array_tag {
    size_t m, n;
    pcc_thunk_t **p;
    pcc_thunk_t *a[PCC_THUNK_ARRAY_MIN_SIZE]; /* for reducing memory allocation frequency */
};

typedef struct pcc_thunk_chunk_tag {
    pcc_value_table_t values;
    pcc_capture_table_t capts;
    pcc_thunk_array_t thunks;
    size_t pos; /* the starting position in the character buffer */
} pcc_thunk_chunk_t;

typedef struct pcc_lr_entry_tag pcc_lr_entry_t;

typedef enum pcc_lr_answer_type_tag {
    PCC_LR_ANSWER_LR,
    PCC_LR_ANSWER_CHUNK
} pcc_lr_answer_type_t;

typedef union pcc_lr_answer_data_tag {
    pcc_lr_entry_t *lr;
    pcc_thunk_chunk_t *chunk;
} pcc_lr_answer_data_t;

typedef struct pcc_lr_answer_tag pcc_lr_answer_t;

struct pcc_lr_answer_tag {
    pcc_lr_answer_type_t type;
    pcc_lr_answer_data_t data;
    size_t pos; /* the absolute position in the input */
    pcc_lr_answer_t *hold;
};

typedef pcc_thunk_chunk_t *(*pcc_rule_t)(pcc_context_t *);

typedef struct pcc_rule_set_tag {
    size_t m, n;
    pcc_rule_t *p;
} pcc_rule_set_t;

typedef struct pcc_lr_head_tag pcc_lr_head_t;

struct pcc_lr_head_tag {
    pcc_rule_t rule;
    pcc_rule_set_t invol;
    pcc_rule_set_t eval;
    pcc_lr_head_t *hold;
};

typedef struct pcc_lr_memo_tag {
    pcc_rule_t rule;
    pcc_lr_answer_t *answer;
} pcc_lr_memo_t;

typedef struct pcc_lr_memo_map_tag {
    size_t m, n;
    pcc_lr_memo_t *p;
    pcc_lr_memo_t a[PCC_LR_MEMO_MAP_MIN_SIZE]; /* for reducing memory allocation frequency */
} pcc_lr_memo_map_t;

typedef struct pcc_lr_table_entry_tag {
    pcc_lr_head_t *head; /* just a reference */
    pcc_lr_memo_map_t memos;
    pcc_lr_answer_t *hold_a;
    pcc_lr_head_t *hold_h;
} pcc_lr_table_entry_t;

typedef struct pcc_lr_table_tag {
    size_t m, n;
    size_t o;
    pcc_lr_table_entry_t **p;
} pcc_lr_table_t;

struct pcc_lr_entry_tag {
    pcc_rule_t rule;
    pcc_thunk_chunk_t *seed; /* just a reference */
    pcc_lr_head_t *head; /* just a reference */
};

typedef struct pcc_lr_stack_tag {
    size_t m, n;
    pcc_lr_entry_t **p;
} pcc_lr_stack_t;

typedef struct pcc_memory_entry_tag pcc_memory_entry_t;
typedef struct pcc_memory_pool_tag pcc_memory_pool_t;

struct pcc_memory_entry_tag {
    pcc_memory_entry_t *next;
};

struct pcc_memory_pool_tag {
    pcc_memory_pool_t *next;
    size_t allocated;
    size_t unused;
};

typedef struct pcc_memory_recycler_tag {
    pcc_memory_pool_t *pool_list;
    pcc_memory_entry_t *entry_list;
    size_t element_size;
} pcc_memory_recycler_t;

struct pcc_context_tag {
    size_t pos; /* the position in the input of the first character currently buffered */
    size_t cur; /* the current parsing position in the character buffer */
    size_t level;
    pcc_char_array_t buffer;
    pcc_lr_table_t lrtable;
    pcc_lr_stack_t lrstack;
    pcc_thunk_array_t thunks;
    pcc_capture_t capt0; /* used only for programmable predicates */
    pcc_auxil_t auxil;
    pcc_memory_recycler_t thunk_recycler;
    pcc_memory_recycler_t thunk_chunk_recycler;
    pcc_memory_recycler_t lr_head_recycler;
    pcc_memory_recycler_t lr_answer_recycler;
    pcc_memory_recycler_t lr_table_entry_recycler;
    pcc_memory_recycler_t lr_entry_recycler;
};

#ifndef PCC_ERROR
#define PCC_ERROR(auxil) pcc_error()
MARK_FUNC_AS_USED
static void pcc_error(void) {
    fprintf(stderr, "Syntax error\n");
    exit(1);
}
#endif /* !PCC_ERROR */

#ifndef PCC_GETCHAR
#define PCC_GETCHAR(auxil) getchar()
#endif /* !PCC_GETCHAR */

#ifndef PCC_MALLOC
#define PCC_MALLOC(auxil, size) pcc_malloc_e(size)
static void *pcc_malloc_e(size_t size) {
    void *const p = malloc(size);
    if (p == NULL) {
        fprintf(stderr, "Out of memory\n");
        exit(1);
    }
    return p;
}
#endif /* !PCC_MALLOC */

#ifndef PCC_REALLOC
#define PCC_REALLOC(auxil, ptr, size) pcc_realloc_e(ptr, size)
static void *pcc_realloc_e(void *ptr, size_t size) {
    void *const p = realloc(ptr, size);
    if (p == NULL) {
        fprintf(stderr, "Out of memory\n");
        exit(1);
    }
    return p;
}
#endif /* !PCC_REALLOC */

#ifndef PCC_FREE
#define PCC_FREE(auxil, ptr) free(ptr)
#endif /* !PCC_FREE */

#ifndef PCC_DEBUG
#define PCC_DEBUG(auxil, event, rule, level, pos, buffer, length) ((void)0)
#endif /* !PCC_DEBUG */

static void pcc_char_array__initialize(pcc_auxil_t auxil, pcc_char_array_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_char_array__finalize(pcc_auxil_t auxil, pcc_char_array_t *obj) {
    PCC_FREE(auxil, obj->p);
}

static void pcc_char_array__resize(pcc_auxil_t auxil, pcc_char_array_t *obj, size_t len) {
    if (obj->m < len) {
        size_t m = obj->m;
        if (m == 0) m = PCC_BUFFER_MIN_SIZE;
        while (m < len && m != 0) m <<= 1;
        if (m == 0) m = len;
        obj->p = (char *)PCC_REALLOC(auxil, obj->p, m);
        obj->m = m;
    }
    obj->n = len;
}

static void pcc_char_array__add(pcc_auxil_t auxil, pcc_char_array_t *obj, char ch) {
    if (obj->m <= obj->n) {
        const size_t n = obj->n + 1;
        size_t m = obj->m;
        if (m == 0) m = PCC_BUFFER_MIN_SIZE;
        while (m < n && m != 0) m <<= 1;
        if (m == 0) m = n;
        obj->p = (char *)PCC_REALLOC(auxil, obj->p, m);
        obj->m = m;
    }
    obj->p[obj->n++] = ch;
}

MARK_FUNC_AS_USED
static void pcc_char_array__copy(pcc_auxil_t auxil, pcc_char_array_t *obj, const pcc_char_array_t *src) {
    if (obj == src) return;
    pcc_char_array__resize(auxil, obj, src->n);
    memcpy(obj->p, src->p, src->n);
}

static void pcc_value_table__initialize(pcc_auxil_t auxil, pcc_value_table_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_value_table__finalize(pcc_auxil_t auxil, pcc_value_table_t *obj) {
    PCC_FREE(auxil, obj->p);
}

MARK_FUNC_AS_USED
static void pcc_value_table__clear(pcc_auxil_t auxil, pcc_value_table_t *obj) {
    memset(obj->p, 0, sizeof(pcc_value_t) * obj->n);
}

MARK_FUNC_AS_USED
static void pcc_value_table__resize(pcc_auxil_t auxil, pcc_value_table_t *obj, size_t len) {
    if (obj->m < len) {
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < len && m != 0) m <<= 1;
        if (m == 0) m = len;
        obj->p = (pcc_value_t *)PCC_REALLOC(auxil, obj->p, sizeof(pcc_value_t) * m);
        obj->m = m;
    }
    obj->n = len;
}

static void pcc_value_refer_table__initialize(pcc_auxil_t auxil, pcc_value_refer_table_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_value_refer_table__finalize(pcc_auxil_t auxil, pcc_value_refer_table_t *obj) {
    PCC_FREE(auxil, obj->p);
}

static void pcc_value_refer_table__resize(pcc_auxil_t auxil, pcc_value_refer_table_t *obj, size_t len) {
    size_t i;
    if (obj->m < len) {
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < len && m != 0) m <<= 1;
        if (m == 0) m = len;
        obj->p = (pcc_value_t **)PCC_REALLOC(auxil, obj->p, sizeof(pcc_value_t *) * m);
        obj->m = m;
    }
    for (i = obj->n; i < len; i++) obj->p[i] = NULL;
    obj->n = len;
}

static void pcc_capture__initialize(pcc_auxil_t auxil, pcc_capture_t *obj) {
    obj->range.start = 0;
    obj->range.end = 0;
    pcc_char_array__initialize(auxil, &(obj->string));
}

static void pcc_capture__finalize(pcc_auxil_t auxil, pcc_capture_t *obj) {
    pcc_char_array__finalize(auxil, &(obj->string));
}

static void pcc_capture_table__initialize(pcc_auxil_t auxil, pcc_capture_table_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_capture_table__finalize(pcc_auxil_t auxil, pcc_capture_table_t *obj) {
    while (obj->n > 0) {
        obj->n--;
        pcc_capture__finalize(auxil, &(obj->p[obj->n]));
    }
    PCC_FREE(auxil, obj->p);
}

MARK_FUNC_AS_USED
static void pcc_capture_table__resize(pcc_auxil_t auxil, pcc_capture_table_t *obj, size_t len) {
    size_t i;
    for (i = len; i < obj->n; i++) pcc_capture__finalize(auxil, &(obj->p[i]));
    if (obj->m < len) {
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < len && m != 0) m <<= 1;
        if (m == 0) m = len;
        obj->p = (pcc_capture_t *)PCC_REALLOC(auxil, obj->p, sizeof(pcc_capture_t) * m);
        obj->m = m;
    }
    for (i = obj->n; i < len; i++) pcc_capture__initialize(auxil, &(obj->p[i]));
    obj->n = len;
}

static void pcc_capture_const_table__initialize(pcc_auxil_t auxil, pcc_capture_const_table_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_capture_const_table__finalize(pcc_auxil_t auxil, pcc_capture_const_table_t *obj) {
    PCC_FREE(auxil, (void *)obj->p);
}

static void pcc_capture_const_table__resize(pcc_auxil_t auxil, pcc_capture_const_table_t *obj, size_t len) {
    size_t i;
    if (obj->m < len) {
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < len && m != 0) m <<= 1;
        if (m == 0) m = len;
        obj->p = (const pcc_capture_t **)PCC_REALLOC(auxil, (pcc_capture_t **)obj->p, sizeof(const pcc_capture_t *) * m);
        obj->m = m;
    }
    for (i = obj->n; i < len; i++) obj->p[i] = NULL;
    obj->n = len;
}

static void pcc_memory_recycler__initialize(pcc_auxil_t auxil, pcc_memory_recycler_t *obj, size_t element_size) {
    obj->pool_list = NULL;
    obj->entry_list = NULL;
    obj->element_size = element_size;
}

static void pcc_memory_recycler__finalize(pcc_auxil_t auxil, pcc_memory_recycler_t *obj) {
    while (obj->pool_list) {
        pcc_memory_pool_t *const pool = obj->pool_list;
        obj->pool_list = pool->next;
        PCC_FREE(auxil, pool);
    }
}

static void *pcc_memory_recycler__supply(pcc_auxil_t auxil, pcc_memory_recycler_t *obj) {
    if (obj->entry_list) {
        pcc_memory_entry_t *const tmp = obj->entry_list;
        obj->entry_list = tmp->next;
        return tmp;
    }
    if (!obj->pool_list || obj->pool_list->unused == 0) {
        size_t size = PCC_POOL_MIN_SIZE;
        if (obj->pool_list) {
            size = obj->pool_list->allocated << 1;
            if (size == 0) size = obj->pool_list->allocated;
        }
        {
            pcc_memory_pool_t *const pool = (pcc_memory_pool_t *)PCC_MALLOC(
                auxil, sizeof(pcc_memory_pool_t) + obj->element_size * size
            );
            pool->allocated = size;
            pool->unused = size;
            pool->next = obj->pool_list;
            obj->pool_list = pool;
        }
    }
    obj->pool_list->unused--;
    return (char *)(obj->pool_list + 1) + obj->element_size * obj->pool_list->unused;
}

static void pcc_memory_recycler__recycle(pcc_auxil_t auxil, pcc_memory_recycler_t *obj, void *ptr) {
    pcc_memory_entry_t *const tmp = (pcc_memory_entry_t *)ptr;
    if (tmp == NULL) return;
    tmp->next = obj->entry_list;
    obj->entry_list = tmp;
}

MARK_FUNC_AS_USED
static pcc_thunk_t *pcc_thunk__create_leaf(pcc_context_t *ctx, pcc_action_t action, size_t valuec, size_t captc) {
    pcc_thunk_t *const obj = (pcc_thunk_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->thunk_recycler));
    obj->type = PCC_THUNK_LEAF;
    pcc_value_refer_table__initialize(ctx->auxil, &(obj->data.leaf.values));
    pcc_value_refer_table__resize(ctx->auxil, &(obj->data.leaf.values), valuec);
    pcc_capture_const_table__initialize(ctx->auxil, &(obj->data.leaf.capts));
    pcc_capture_const_table__resize(ctx->auxil, &(obj->data.leaf.capts), captc);
    pcc_capture__initialize(ctx->auxil, &(obj->data.leaf.capt0));
    obj->data.leaf.action = action;
    return obj;
}

static pcc_thunk_t *pcc_thunk__create_node(pcc_context_t *ctx, const pcc_thunk_array_t *thunks, pcc_value_t *value) {
    pcc_thunk_t *const obj = (pcc_thunk_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->thunk_recycler));
    obj->type = PCC_THUNK_NODE;
    obj->data.node.thunks = thunks;
    obj->data.node.value = value;
    return obj;
}

static void pcc_thunk__destroy(pcc_context_t *ctx, pcc_thunk_t *obj) {
    if (obj == NULL) return;
    switch (obj->type) {
    case PCC_THUNK_LEAF:
        pcc_value_refer_table__finalize(ctx->auxil, &(obj->data.leaf.values));
        pcc_capture_const_table__finalize(ctx->auxil, &(obj->data.leaf.capts));
        pcc_capture__finalize(ctx->auxil, &(obj->data.leaf.capt0));
        break;
    case PCC_THUNK_NODE:
        break;
    default: /* unknown */
        break;
    }
    pcc_memory_recycler__recycle(ctx->auxil, &(ctx->thunk_recycler), obj);
}

static void pcc_thunk_array__initialize(pcc_context_t *ctx, pcc_thunk_array_t *obj) {
    obj->m = PCC_THUNK_ARRAY_MIN_SIZE;
    obj->n = 0;
    obj->p = obj->a;
}

static void pcc_thunk_array__finalize(pcc_context_t *ctx, pcc_thunk_array_t *obj) {
    while (obj->n > 0) {
        obj->n--;
        pcc_thunk__destroy(ctx, obj->p[obj->n]);
    }
    if (obj->p != obj->a) PCC_FREE(ctx->auxil, obj->p);
}

static void pcc_thunk_array__add(pcc_context_t *ctx, pcc_thunk_array_t *obj, pcc_thunk_t *thunk) {
    if (obj->m <= obj->n) {
        const size_t n = obj->n + 1;
        size_t m = obj->m;
        if (m == 0) m = PCC_THUNK_ARRAY_MIN_SIZE << 1;
        while (m < n && m != 0) m <<= 1;
        if (m == 0) m = n;
        if (obj->p == obj->a) {
            size_t i;
            obj->p = (pcc_thunk_t **)PCC_MALLOC(ctx->auxil, sizeof(pcc_thunk_t *) * m);
            for (i = 0; i < PCC_THUNK_ARRAY_MIN_SIZE; i++) obj->p[i] = obj->a[i];
        }
        else {
            obj->p = (pcc_thunk_t **)PCC_REALLOC(ctx->auxil, obj->p, sizeof(pcc_thunk_t *) * m);
        }
        obj->m = m;
    }
    obj->p[obj->n++] = thunk;
}

static void pcc_thunk_array__revert(pcc_context_t *ctx, pcc_thunk_array_t *obj, size_t len) {
    while (obj->n > len) {
        obj->n--;
        pcc_thunk__destroy(ctx, obj->p[obj->n]);
    }
}

MARK_FUNC_AS_USED
static pcc_thunk_chunk_t *pcc_thunk_chunk__create(pcc_context_t *ctx) {
    pcc_thunk_chunk_t *const obj = (pcc_thunk_chunk_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->thunk_chunk_recycler));
    pcc_value_table__initialize(ctx->auxil, &(obj->values));
    pcc_capture_table__initialize(ctx->auxil, &(obj->capts));
    pcc_thunk_array__initialize(ctx, &(obj->thunks));
    obj->pos = 0;
    return obj;
}

static void pcc_thunk_chunk__destroy(pcc_context_t *ctx, pcc_thunk_chunk_t *obj) {
    if (obj == NULL) return;
    pcc_value_table__finalize(ctx->auxil, &(obj->values));
    pcc_capture_table__finalize(ctx->auxil, &(obj->capts));
    pcc_thunk_array__finalize(ctx, &(obj->thunks));
    pcc_memory_recycler__recycle(ctx->auxil, &(ctx->thunk_chunk_recycler), obj);
}

static void pcc_rule_set__initialize(pcc_auxil_t auxil, pcc_rule_set_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_rule_set__finalize(pcc_auxil_t auxil, pcc_rule_set_t *obj) {
    PCC_FREE(auxil, obj->p);
}

static void pcc_rule_set__clear(pcc_auxil_t auxil, pcc_rule_set_t *obj) {
    obj->n = 0;
}

static size_t pcc_rule_set__index(pcc_auxil_t auxil, const pcc_rule_set_t *obj, pcc_rule_t rule) {
    size_t i;
    for (i = 0; i < obj->n; i++) {
        if (obj->p[i] == rule) return i;
    }
    return PCC_VOID_VALUE;
}

static pcc_bool_t pcc_rule_set__add(pcc_auxil_t auxil, pcc_rule_set_t *obj, pcc_rule_t rule) {
    const size_t i = pcc_rule_set__index(auxil, obj, rule);
    if (i != PCC_VOID_VALUE) return PCC_FALSE;
    if (obj->m <= obj->n) {
        const size_t n = obj->n + 1;
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < n && m != 0) m <<= 1;
        if (m == 0) m = n;
        obj->p = (pcc_rule_t *)PCC_REALLOC(auxil, obj->p, sizeof(pcc_rule_t) * m);
        obj->m = m;
    }
    obj->p[obj->n++] = rule;
    return PCC_TRUE;
}

static pcc_bool_t pcc_rule_set__remove(pcc_auxil_t auxil, pcc_rule_set_t *obj, pcc_rule_t rule) {
    const size_t i = pcc_rule_set__index(auxil, obj, rule);
    if (i == PCC_VOID_VALUE) return PCC_FALSE;
    memmove(obj->p + i, obj->p + (i + 1), sizeof(pcc_rule_t) * (obj->n - (i + 1)));
    return PCC_TRUE;
}

static void pcc_rule_set__copy(pcc_auxil_t auxil, pcc_rule_set_t *obj, const pcc_rule_set_t *src) {
    size_t i;
    if (obj == src) return;
    pcc_rule_set__clear(auxil, obj);
    for (i = 0; i < src->n; i++) {
        pcc_rule_set__add(auxil, obj, src->p[i]);
    }
}

static pcc_lr_head_t *pcc_lr_head__create(pcc_context_t *ctx, pcc_rule_t rule) {
    pcc_lr_head_t *const obj = (pcc_lr_head_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->lr_head_recycler));
    obj->rule = rule;
    pcc_rule_set__initialize(ctx->auxil, &(obj->invol));
    pcc_rule_set__initialize(ctx->auxil, &(obj->eval));
    obj->hold = NULL;
    return obj;
}

static void pcc_lr_head__destroy(pcc_context_t *ctx, pcc_lr_head_t *obj) {
    if (obj == NULL) return;
    pcc_rule_set__finalize(ctx->auxil, &(obj->invol));
    pcc_rule_set__finalize(ctx->auxil, &(obj->eval));
    pcc_lr_head__destroy(ctx, obj->hold);
    pcc_memory_recycler__recycle(ctx->auxil, &(ctx->lr_head_recycler), obj);
}

static void pcc_lr_entry__destroy(pcc_context_t *ctx, pcc_lr_entry_t *lr);

static pcc_lr_answer_t *pcc_lr_answer__create(pcc_context_t *ctx, pcc_lr_answer_type_t type, size_t pos) {
    pcc_lr_answer_t *obj = (pcc_lr_answer_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->lr_answer_recycler));
    obj->type = type;
    obj->pos = pos;
    obj->hold = NULL;
    switch (obj->type) {
    case PCC_LR_ANSWER_LR:
        obj->data.lr = NULL;
        break;
    case PCC_LR_ANSWER_CHUNK:
        obj->data.chunk = NULL;
        break;
    default: /* unknown */
        pcc_memory_recycler__recycle(ctx->auxil, &(ctx->lr_answer_recycler), obj);
        obj = NULL;
    }
    return obj;
}

static void pcc_lr_answer__destroy(pcc_context_t *ctx, pcc_lr_answer_t *obj) {
    while (obj != NULL) {
        pcc_lr_answer_t *const a = obj->hold;
        switch (obj->type) {
        case PCC_LR_ANSWER_LR:
            pcc_lr_entry__destroy(ctx, obj->data.lr);
            break;
        case PCC_LR_ANSWER_CHUNK:
            pcc_thunk_chunk__destroy(ctx, obj->data.chunk);
            break;
        default: /* unknown */
            break;
        }
        pcc_memory_recycler__recycle(ctx->auxil, &(ctx->lr_answer_recycler), obj);
        obj = a;
    }
}

static void pcc_lr_answer__set_chunk(pcc_context_t *ctx, pcc_lr_answer_t *obj, pcc_thunk_chunk_t *chunk) {
    pcc_lr_answer_t *const a = pcc_lr_answer__create(ctx, obj->type, obj->pos);
    switch (obj->type) {
    case PCC_LR_ANSWER_LR:
        a->data.lr = obj->data.lr;
        break;
    case PCC_LR_ANSWER_CHUNK:
        a->data.chunk = obj->data.chunk;
        break;
    default: /* unknown */
        break;
    }
    a->hold = obj->hold;
    obj->hold = a;
    obj->type = PCC_LR_ANSWER_CHUNK;
    obj->data.chunk = chunk;
}

static void pcc_lr_memo_map__initialize(pcc_context_t *ctx, pcc_lr_memo_map_t *obj) {
    obj->m = PCC_LR_MEMO_MAP_MIN_SIZE;
    obj->n = 0;
    obj->p = obj->a;
}

static void pcc_lr_memo_map__finalize(pcc_context_t *ctx, pcc_lr_memo_map_t *obj) {
    while (obj->n > 0) {
        obj->n--;
        pcc_lr_answer__destroy(ctx, obj->p[obj->n].answer);
    }
    if (obj->p != obj->a) PCC_FREE(ctx->auxil, obj->p);
}

static size_t pcc_lr_memo_map__index(pcc_context_t *ctx, pcc_lr_memo_map_t *obj, pcc_rule_t rule) {
    size_t i;
    for (i = 0; i < obj->n; i++) {
        if (obj->p[i].rule == rule) return i;
    }
    return PCC_VOID_VALUE;
}

static void pcc_lr_memo_map__put(pcc_context_t *ctx, pcc_lr_memo_map_t *obj, pcc_rule_t rule, pcc_lr_answer_t *answer) {
    const size_t i = pcc_lr_memo_map__index(ctx, obj, rule);
    if (i != PCC_VOID_VALUE) {
        pcc_lr_answer__destroy(ctx, obj->p[i].answer);
        obj->p[i].answer = answer;
    }
    else {
        if (obj->m <= obj->n) {
            const size_t n = obj->n + 1;
            size_t m = obj->m;
            if (m == 0) m = PCC_LR_MEMO_MAP_MIN_SIZE << 1;
            while (m < n && m != 0) m <<= 1;
            if (m == 0) m = n;
            if (obj->p == obj->a) {
                size_t i;
                obj->p = (pcc_lr_memo_t *)PCC_MALLOC(ctx->auxil, sizeof(pcc_lr_memo_t) * m);
                for (i = 0; i < PCC_LR_MEMO_MAP_MIN_SIZE; i++) obj->p[i] = obj->a[i];
            }
            else {
                obj->p = (pcc_lr_memo_t *)PCC_REALLOC(ctx->auxil, obj->p, sizeof(pcc_lr_memo_t) * m);
            }
            obj->m = m;
        }
        obj->p[obj->n].rule = rule;
        obj->p[obj->n].answer = answer;
        obj->n++;
    }
}

static pcc_lr_answer_t *pcc_lr_memo_map__get(pcc_context_t *ctx, pcc_lr_memo_map_t *obj, pcc_rule_t rule) {
    const size_t i = pcc_lr_memo_map__index(ctx, obj, rule);
    return (i != PCC_VOID_VALUE) ? obj->p[i].answer : NULL;
}

static pcc_lr_table_entry_t *pcc_lr_table_entry__create(pcc_context_t *ctx) {
    pcc_lr_table_entry_t *const obj = (pcc_lr_table_entry_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->lr_table_entry_recycler));
    obj->head = NULL;
    pcc_lr_memo_map__initialize(ctx, &(obj->memos));
    obj->hold_a = NULL;
    obj->hold_h = NULL;
    return obj;
}

static void pcc_lr_table_entry__destroy(pcc_context_t *ctx, pcc_lr_table_entry_t *obj) {
    if (obj == NULL) return;
    pcc_lr_memo_map__finalize(ctx, &(obj->memos));
    pcc_lr_answer__destroy(ctx, obj->hold_a);
    pcc_lr_head__destroy(ctx, obj->hold_h);
    pcc_memory_recycler__recycle(ctx->auxil, &(ctx->lr_table_entry_recycler), obj);
}

static void pcc_lr_table__initialize(pcc_context_t *ctx, pcc_lr_table_t *obj) {
    obj->o = 0;
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_lr_table__finalize(pcc_context_t *ctx, pcc_lr_table_t *obj) {
    while (obj->n > obj->o) {
        obj->n--;
        pcc_lr_table_entry__destroy(ctx, obj->p[obj->n]);
    }
    PCC_FREE(ctx->auxil, obj->p);
}

static void pcc_lr_table__resize(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t len) {
    size_t i;
    for (i = len; i < obj->n; i++) pcc_lr_table_entry__destroy(ctx, obj->p[i]);
    if (obj->m < len) {
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < len && m != 0) m <<= 1;
        if (m == 0) m = len;
        obj->p = (pcc_lr_table_entry_t **)PCC_REALLOC(ctx->auxil, obj->p, sizeof(pcc_lr_table_entry_t *) * m);
        obj->m = m;
    }
    for (i = obj->n; i < len; i++) obj->p[i] = NULL;
    obj->n = len;
}

static void pcc_lr_table__set_head(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t index, pcc_lr_head_t *head) {
    index += obj->o;
    if (index >= obj->n) pcc_lr_table__resize(ctx, obj, index + 1);
    if (obj->p[index] == NULL) obj->p[index] = pcc_lr_table_entry__create(ctx);
    obj->p[index]->head = head;
}

static void pcc_lr_table__hold_head(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t index, pcc_lr_head_t *head) {
    index += obj->o;
    if (index >= obj->n) pcc_lr_table__resize(ctx, obj, index + 1);
    if (obj->p[index] == NULL) obj->p[index] = pcc_lr_table_entry__create(ctx);
    head->hold = obj->p[index]->hold_h;
    obj->p[index]->hold_h = head;
}

static void pcc_lr_table__set_answer(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t index, pcc_rule_t rule, pcc_lr_answer_t *answer) {
    index += obj->o;
    if (index >= obj->n) pcc_lr_table__resize(ctx, obj, index + 1);
    if (obj->p[index] == NULL) obj->p[index] = pcc_lr_table_entry__create(ctx);
    pcc_lr_memo_map__put(ctx, &(obj->p[index]->memos), rule, answer);
}

static void pcc_lr_table__hold_answer(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t index, pcc_lr_answer_t *answer) {
    index += obj->o;
    if (index >= obj->n) pcc_lr_table__resize(ctx, obj, index + 1);
    if (obj->p[index] == NULL) obj->p[index] = pcc_lr_table_entry__create(ctx);
    answer->hold = obj->p[index]->hold_a;
    obj->p[index]->hold_a = answer;
}

static pcc_lr_head_t *pcc_lr_table__get_head(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t index) {
    index += obj->o;
    if (index >= obj->n || obj->p[index] == NULL) return NULL;
    return obj->p[index]->head;
}

static pcc_lr_answer_t *pcc_lr_table__get_answer(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t index, pcc_rule_t rule) {
    index += obj->o;
    if (index >= obj->n || obj->p[index] == NULL) return NULL;
    return pcc_lr_memo_map__get(ctx, &(obj->p[index]->memos), rule);
}

static void pcc_lr_table__shift(pcc_context_t *ctx, pcc_lr_table_t *obj, size_t count) {
    size_t i;
    if (count > obj->n - obj->o) count = obj->n - obj->o;
    for (i = 0; i < count; i++) pcc_lr_table_entry__destroy(ctx, obj->p[obj->o++]);
    if (obj->o > (obj->m >> 1)) {
        memmove(obj->p, obj->p + obj->o, sizeof(pcc_lr_table_entry_t *) * (obj->n - obj->o));
        obj->n -= obj->o;
        obj->o = 0;
    }
}

static pcc_lr_entry_t *pcc_lr_entry__create(pcc_context_t *ctx, pcc_rule_t rule) {
    pcc_lr_entry_t *const lr = (pcc_lr_entry_t *)pcc_memory_recycler__supply(ctx->auxil, &(ctx->lr_entry_recycler));
    lr->rule = rule;
    lr->seed = NULL;
    lr->head = NULL;
    return lr;
}

static void pcc_lr_entry__destroy(pcc_context_t *ctx, pcc_lr_entry_t *lr) {
    pcc_memory_recycler__recycle(ctx->auxil, &(ctx->lr_entry_recycler), lr);
}

static void pcc_lr_stack__initialize(pcc_auxil_t auxil, pcc_lr_stack_t *obj) {
    obj->m = 0;
    obj->n = 0;
    obj->p = NULL;
}

static void pcc_lr_stack__finalize(pcc_auxil_t auxil, pcc_lr_stack_t *obj) {
    PCC_FREE(auxil, obj->p);
}

static void pcc_lr_stack__push(pcc_auxil_t auxil, pcc_lr_stack_t *obj, pcc_lr_entry_t *lr) {
    if (obj->m <= obj->n) {
        const size_t n = obj->n + 1;
        size_t m = obj->m;
        if (m == 0) m = PCC_ARRAY_MIN_SIZE;
        while (m < n && m != 0) m <<= 1;
        if (m == 0) m = n;
        obj->p = (pcc_lr_entry_t **)PCC_REALLOC(auxil, obj->p, sizeof(pcc_lr_entry_t *) * m);
        obj->m = m;
    }
    obj->p[obj->n++] = lr;
}

static pcc_lr_entry_t *pcc_lr_stack__pop(pcc_auxil_t auxil, pcc_lr_stack_t *obj) {
    return obj->p[--obj->n];
}

static pcc_context_t *pcc_context__create(pcc_auxil_t auxil) {
    pcc_context_t *const ctx = (pcc_context_t *)PCC_MALLOC(auxil, sizeof(pcc_context_t));
    ctx->pos = 0;
    ctx->cur = 0;
    ctx->level = 0;
    pcc_char_array__initialize(auxil, &(ctx->buffer));
    pcc_lr_table__initialize(ctx, &(ctx->lrtable));
    pcc_lr_stack__initialize(auxil, &(ctx->lrstack));
    pcc_thunk_array__initialize(ctx, &(ctx->thunks));
    pcc_capture__initialize(ctx->auxil, &(ctx->capt0));
    pcc_memory_recycler__initialize(auxil, &(ctx->thunk_recycler), sizeof(pcc_thunk_t));
    pcc_memory_recycler__initialize(auxil, &(ctx->thunk_chunk_recycler), sizeof(pcc_thunk_chunk_t));
    pcc_memory_recycler__initialize(auxil, &(ctx->lr_head_recycler), sizeof(pcc_lr_head_t));
    pcc_memory_recycler__initialize(auxil, &(ctx->lr_answer_recycler), sizeof(pcc_lr_answer_t));
    pcc_memory_recycler__initialize(auxil, &(ctx->lr_table_entry_recycler), sizeof(pcc_lr_table_entry_t));
    pcc_memory_recycler__initialize(auxil, &(ctx->lr_entry_recycler), sizeof(pcc_lr_entry_t));
    ctx->auxil = auxil;
    return ctx;
}

static void pcc_context__destroy(pcc_context_t *ctx) {
    if (ctx == NULL) return;
    pcc_char_array__finalize(ctx->auxil, &(ctx->buffer));
    pcc_lr_table__finalize(ctx, &(ctx->lrtable));
    pcc_lr_stack__finalize(ctx->auxil, &(ctx->lrstack));
    pcc_thunk_array__finalize(ctx, &(ctx->thunks));
    pcc_capture__finalize(ctx->auxil, &(ctx->capt0));
    pcc_memory_recycler__finalize(ctx->auxil, &(ctx->thunk_recycler));
    pcc_memory_recycler__finalize(ctx->auxil, &(ctx->thunk_chunk_recycler));
    pcc_memory_recycler__finalize(ctx->auxil, &(ctx->lr_head_recycler));
    pcc_memory_recycler__finalize(ctx->auxil, &(ctx->lr_answer_recycler));
    pcc_memory_recycler__finalize(ctx->auxil, &(ctx->lr_table_entry_recycler));
    pcc_memory_recycler__finalize(ctx->auxil, &(ctx->lr_entry_recycler));
    PCC_FREE(ctx->auxil, ctx);
}

static size_t pcc_refill_buffer(pcc_context_t *ctx, size_t num) {
    if (ctx->buffer.n >= ctx->cur + num) return ctx->buffer.n - ctx->cur;
    while (ctx->buffer.n < ctx->cur + num) {
        const int c = PCC_GETCHAR(ctx->auxil);
        if (c < 0) break;
        pcc_char_array__add(ctx->auxil, &(ctx->buffer), (char)c);
    }
    return ctx->buffer.n - ctx->cur;
}

MARK_FUNC_AS_USED
static void pcc_commit_buffer(pcc_context_t *ctx) {
    memmove(ctx->buffer.p, ctx->buffer.p + ctx->cur, ctx->buffer.n - ctx->cur);
    ctx->buffer.n -= ctx->cur;
    ctx->pos += ctx->cur;
    pcc_lr_table__shift(ctx, &(ctx->lrtable), ctx->cur);
    ctx->cur = 0;
}

MARK_FUNC_AS_USED
static const char *pcc_get_capture_string(pcc_context_t *ctx, const pcc_capture_t *capt) {
    if (capt->string.n == 0) {
        const size_t n = capt->range.end - capt->range.start;
        pcc_capture_t *const p = (pcc_capture_t *)capt;
        pcc_char_array__resize(ctx->auxil, &(p->string), n + 1);
        if (n > 0) memcpy(p->string.p, ctx->buffer.p + capt->range.start, n);
        p->string.p[n] = '\0';
    }
    return capt->string.p;
}

MARK_FUNC_AS_USED
static pcc_bool_t pcc_apply_rule(pcc_context_t *ctx, pcc_rule_t rule, pcc_thunk_array_t *thunks, pcc_value_t *value) {
    static pcc_value_t null;
    pcc_thunk_chunk_t *c = NULL;
    const size_t p = ctx->pos + ctx->cur;
    pcc_bool_t b = PCC_TRUE;
    pcc_lr_answer_t *a = pcc_lr_table__get_answer(ctx, &(ctx->lrtable), p, rule);
    pcc_lr_head_t *h = pcc_lr_table__get_head(ctx, &(ctx->lrtable), p);
    if (h != NULL) {
        if (a == NULL && rule != h->rule && pcc_rule_set__index(ctx->auxil, &(h->invol), rule) == PCC_VOID_VALUE) {
            b = PCC_FALSE;
            c = NULL;
        }
        else if (pcc_rule_set__remove(ctx->auxil, &(h->eval), rule)) {
            b = PCC_FALSE;
            c = rule(ctx);
            a = pcc_lr_answer__create(ctx, PCC_LR_ANSWER_CHUNK, ctx->pos + ctx->cur);
            a->data.chunk = c;
            pcc_lr_table__hold_answer(ctx, &(ctx->lrtable), p, a);
        }
    }
    if (b) {
        if (a != NULL) {
            ctx->cur = a->pos - ctx->pos;
            switch (a->type) {
            case PCC_LR_ANSWER_LR:
                if (a->data.lr->head == NULL) {
                    a->data.lr->head = pcc_lr_head__create(ctx, rule);
                    pcc_lr_table__hold_head(ctx, &(ctx->lrtable), p, a->data.lr->head);
                }
                {
                    size_t i = ctx->lrstack.n;
                    while (i > 0) {
                        i--;
                        if (ctx->lrstack.p[i]->head == a->data.lr->head) break;
                        ctx->lrstack.p[i]->head = a->data.lr->head;
                        pcc_rule_set__add(ctx->auxil, &(a->data.lr->head->invol), ctx->lrstack.p[i]->rule);
                    }
                }
                c = a->data.lr->seed;
                break;
            case PCC_LR_ANSWER_CHUNK:
                c = a->data.chunk;
                break;
            default: /* unknown */
                break;
            }
        }
        else {
            pcc_lr_entry_t *const e = pcc_lr_entry__create(ctx, rule);
            pcc_lr_stack__push(ctx->auxil, &(ctx->lrstack), e);
            a = pcc_lr_answer__create(ctx, PCC_LR_ANSWER_LR, p);
            a->data.lr = e;
            pcc_lr_table__set_answer(ctx, &(ctx->lrtable), p, rule, a);
            c = rule(ctx);
            pcc_lr_stack__pop(ctx->auxil, &(ctx->lrstack));
            a->pos = ctx->pos + ctx->cur;
            if (e->head == NULL) {
                pcc_lr_answer__set_chunk(ctx, a, c);
            }
            else {
                e->seed = c;
                h = a->data.lr->head;
                if (h->rule != rule) {
                    c = a->data.lr->seed;
                    a = pcc_lr_answer__create(ctx, PCC_LR_ANSWER_CHUNK, ctx->pos + ctx->cur);
                    a->data.chunk = c;
                    pcc_lr_table__hold_answer(ctx, &(ctx->lrtable), p, a);
                }
                else {
                    pcc_lr_answer__set_chunk(ctx, a, a->data.lr->seed);
                    if (a->data.chunk == NULL) {
                        c = NULL;
                    }
                    else {
                        pcc_lr_table__set_head(ctx, &(ctx->lrtable), p, h);
                        for (;;) {
                            ctx->cur = p - ctx->pos;
                            pcc_rule_set__copy(ctx->auxil, &(h->eval), &(h->invol));
                            c = rule(ctx);
                            if (c == NULL || ctx->pos + ctx->cur <= a->pos) break;
                            pcc_lr_answer__set_chunk(ctx, a, c);
                            a->pos = ctx->pos + ctx->cur;
                        }
                        pcc_thunk_chunk__destroy(ctx, c);
                        pcc_lr_table__set_head(ctx, &(ctx->lrtable), p, NULL);
                        ctx->cur = a->pos - ctx->pos;
                        c = a->data.chunk;
                    }
                }
            }
        }
    }
    if (c == NULL) return PCC_FALSE;
    if (value == NULL) value = &null;
    memset(value, 0, sizeof(pcc_value_t)); /* in case */
    pcc_thunk_array__add(ctx, thunks, pcc_thunk__create_node(ctx, &(c->thunks), value));
    return PCC_TRUE;
}

MARK_FUNC_AS_USED
static void pcc_do_action(pcc_context_t *ctx, const pcc_thunk_array_t *thunks, pcc_value_t *value) {
    size_t i;
    for (i = 0; i < thunks->n; i++) {
        pcc_thunk_t *const thunk = thunks->p[i];
        switch (thunk->type) {
        case PCC_THUNK_LEAF:
            thunk->data.leaf.action(ctx, thunk, value);
            break;
        case PCC_THUNK_NODE:
            pcc_do_action(ctx, thunk->data.node.thunks, thunk->data.node.value);
            break;
        default: /* unknown */
            break;
        }
    }
}

MARK_FUNC_AS_USED
static pcc_auxil_t pcc_ref_auxil_(pcc_context_t *ctx) {
    return ctx->auxil;
}

MARK_FUNC_AS_USED
static const char *pcc_ref_capture_0_(pcc_context_t *ctx) {
    return pcc_get_capture_string(ctx, &(ctx->capt0));
}

MARK_FUNC_AS_USED
static size_t pcc_ref_capture_0s_(pcc_context_t *ctx) {
    return ctx->pos + ctx->capt0.range.start;
}

MARK_FUNC_AS_USED
static size_t pcc_ref_capture_0e_(pcc_context_t *ctx) {
    return ctx->pos + ctx->capt0.range.end;
}

MARK_FUNC_AS_USED
static const char *pcc_ref_capture_(pcc_context_t *ctx, pcc_thunk_chunk_t *in, size_t index) {
    return pcc_get_capture_string(ctx, &(in->capts.p[index]));
}

MARK_FUNC_AS_USED
static size_t pcc_ref_capture_s_(pcc_context_t *ctx, pcc_thunk_chunk_t *in, size_t index) {
    return ctx->pos + in->capts.p[index].range.start;
}

MARK_FUNC_AS_USED
static size_t pcc_ref_capture_e_(pcc_context_t *ctx, pcc_thunk_chunk_t *in, size_t index) {
    return ctx->pos + in->capts.p[index].range.end;
}

MARK_FUNC_AS_USED
static const char *pcc_ref_leaf_capture_0_(pcc_context_t *ctx, pcc_thunk_t *in) {
    return pcc_get_capture_string(ctx, &(in->data.leaf.capt0));
}

MARK_FUNC_AS_USED
static size_t pcc_ref_leaf_capture_0s_(pcc_context_t *ctx, pcc_thunk_t *in) {
    return ctx->pos + in->data.leaf.capt0.range.start;
}

MARK_FUNC_AS_USED
static size_t pcc_ref_leaf_capture_0e_(pcc_context_t *ctx, pcc_thunk_t *in) {
    return ctx->pos + in->data.leaf.capt0.range.end;
}

MARK_FUNC_AS_USED
static const char *pcc_ref_leaf_capture_(pcc_context_t *ctx, pcc_thunk_t *in, size_t index) {
    return pcc_get_capture_string(ctx, in->data.leaf.capts.p[index]);
}

MARK_FUNC_AS_USED
static size_t pcc_ref_leaf_capture_s_(pcc_context_t *ctx, pcc_thunk_t *in, size_t index) {
    return ctx->pos + in->data.leaf.capts.p[index]->range.start;
}

MARK_FUNC_AS_USED
static size_t pcc_ref_leaf_capture_e_(pcc_context_t *ctx, pcc_thunk_t *in, size_t index) {
    return ctx->pos + in->data.leaf.capts.p[index]->range.end;
}

MARK_FUNC_AS_USED
static pcc_value_t *pcc_ref_leaf_variable_(pcc_context_t *ctx, pcc_thunk_t *in, size_t index) {
    return in->data.leaf.values.p[index];
}


pcc_context_t *pcc_create(void *auxil) {
    return pcc_context__create(auxil);
}

int pcc_parse(pcc_context_t *ctx, int *ret) {
    if (pcc_refill_buffer(ctx, 1) < 1) return 0;
    pcc_thunk_array__revert(ctx, &(ctx->thunks), 0);
    return 1;
}

void pcc_destroy(pcc_context_t *ctx) {
    pcc_context__destroy(ctx);
}
