name: cross compile for Android on Ubuntu

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true

      - run: sudo apt-get -y update
      - run: sudo apt-get -y install cmake make

      - run: cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-33 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake

      - run: cmake --build build

      - run: readelf -h build/pegof
      - run: readelf -h build/pegof | grep AArch64
      - run: readelf -d build/pegof
