name: Build and test

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        compiler: [g++, clang]

    runs-on: ${{ matrix.os }}
    env:
      BUILDDIR: ${{ matrix.os }}-${{ matrix.compiler }}
      OS: ${{ matrix.os }}
      COMPILER: ${{ matrix.compiler }}
      DEBIAN_FRONTEND: noninteractive
      CMAKE_BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install dependencies
      shell: bash
      run: |
        set -ex
        DEPS=(cmake bats)
        if [ "$COMPILER" = "g++" ]; then
            DEPS+=(g++)
        else
            DEPS+=(clang llvm)
            if [ "$OS" = "ubuntu-24.04" ]; then
                DEPS+=(libclang-rt-dev)
            else
                DEPS+=(libclang-dev)
            fi
        fi
        sudo apt-get update
        sudo apt-get -y --no-install-recommends -o APT::Immediate-Configure=false install "${DEPS[@]}"
    - name: Build
      shell: bash
      run: |
        set -ex
        cmake -C "$COMPILER.cmake" -B "./$BUILDDIR"
        cmake --build "./$BUILDDIR" --verbose
    - name: Test
      shell: bash
      run: cmake --build "./$BUILDDIR" --target test --verbose
