name: Build and test

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        compiler: [g++, clang]

    runs-on: ${{ matrix.os }}
    env:
      BUILDDIR: ${{ matrix.os }}-${{ matrix.compiler }}
      OS: ${{ matrix.os }}
      COMPILER: ${{ matrix.compiler }}
      DEBIAN_FRONTEND: noninteractive
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install dependencies
      shell: bash
      run: |
        set -ex
        DEPS=(cmake bats)
        if [ "$COMPILER" = "g++" ]; then
            DEPS+=(g++)
        else
            DEPS+=(clang llvm)
            if [ "$OS" = "ubuntu-24.04" ]; then
                DEPS+=(libclang-rt-dev)
            else
                DEPS+=(libclang-dev)
            fi
        fi
        sudo apt-get update
        sudo apt-get -y --no-install-recommends -o APT::Immediate-Configure=false install "${DEPS[@]}"
    - name: Build
      shell: bash
      run: |
        set -ex
        cmake -C "$COMPILER.cmake" -B "./$BUILDDIR"
        cmake --build "./$BUILDDIR" --verbose
    - name: Test
      shell: bash
      run: cmake --build "./$BUILDDIR" --target test --verbose

  slow_tests:
    runs-on: 'ubuntu-24.04'
    env:
      BUILDDIR: build.d
      DEBIAN_FRONTEND: noninteractive
      CMAKE_BUILD_TYPE: Release
      INCLUDE_SLOW_TESTS: "1"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install dependencies
      shell: bash
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get -y --no-install-recommends -o APT::Immediate-Configure=false install g++ cmake make parallel curl
        curl -OL http://azure.archive.ubuntu.com/ubuntu/pool/universe/b/bats/bats_1.11.0-1_all.deb
        sudo dpkg -i bats_1.11.0-1_all.deb
    - name: Build
      shell: bash
      run: |
        set -ex
        cmake -C "g++.cmake" -B "./$BUILDDIR"
        cmake --build "./$BUILDDIR" --verbose
    - name: Run all tests
      shell: bash
      run: |
        set -ex
        git config --global --add safe.directory "$PWD/tests/ctags.d/ctags.git"
        BUILDDIR="$PWD/$BUILDDIR" ./tests/run.sh -j $(nproc || echo "1")
