name: build and test

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [g++, clang]

    runs-on: ${{ matrix.os }}
    env:
      BUILDDIR: ${{ matrix.os }}-${{ matrix.compiler }}
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: update package information
      run: sudo apt-get update
    - name: install tools
      if: matrix.compiler == 'g++'
      run: sudo apt-get -y --no-install-recommends -o APT::Immediate-Configure=false install g++ gcovr cmake bats uncrustify
    - name: install tools
      if: matrix.compiler == 'clang'
      run: sudo apt-get -y --no-install-recommends -o APT::Immediate-Configure=false install clang llvm libclang-rt-dev cmake bats uncrustify
    - name: cmake -B
      run: cmake -C ${{ matrix.compiler }}.cmake -B ./$BUILDDIR
    - name: build
      run: cmake --build ./$BUILDDIR -- VERBOSE=1
    - name: test
      run: cmake --build ./$BUILDDIR --target test
