name: build and test on MSYS2

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  debug:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MINGW32, MINGW64, CLANG32, CLANG64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: cmake make
          pacboy: toolchain:p

      - run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true

      - run: cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON

      - run: cmake --build build --target test_all benchmark

  release:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MINGW32, MINGW64, CLANG32, CLANG64]
        opt: ['', '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE']

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: cmake make

      - run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true

      - run: cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release ${{ matrix.opt }}

      - run: cmake --build build

      - run: build/pegof --help
      - run: build/pegof --version
